---
abstract: 'launch your test in parallel'
author:
  - 'Nicolas R. <atoomic@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Parallel
recommends:
  Sys::Statistics::Linux::MemStats: 0
requires:
  Parallel::ForkManager: 0
  Sys::Info: 0
  Sys::Statistics::Linux::MemStats: 0
  Test::More: 0
  strict: 0
  warnings: 0
version: 0.20
